#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("lcg_srand");       #     <-- Task0
entry("lcg_rand");        #     <-- Task0
entry("setgid");          #     <-- Task1
entry("getgid");          #     <-- Task1
entry("israeli_create");  #     <-- Task1
entry("israeli_acquire"); #     <-- Task1
entry("israeli_release"); #     <-- Task1
entry("israeli_destroy"); #     <-- Task1
entry("relay_reset");     #     <-- Task2
entry("relay_inc");       #     <-- Task2
entry("relay_get");       #     <-- Task2
entry("relay_winner");    #     <-- Task2